"""initial schema

Revision ID: 1dcaef872366
Revises: 
Create Date: 2026-03-14 16:24:31.723015

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '1dcaef872366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_entity_id'), 'bookmarks', ['entity_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_entity_type'), 'bookmarks', ['entity_type'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_definition', sa.Text(), nullable=False),
    sa.Column('detailed_explanation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_name'), 'concepts', ['name'], unique=True)
    op.create_table('content_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_chunks_entity_id'), 'content_chunks', ['entity_id'], unique=False)
    op.create_index(op.f('ix_content_chunks_entity_type'), 'content_chunks', ['entity_type'], unique=False)
    op.create_index(op.f('ix_content_chunks_source_label'), 'content_chunks', ['source_label'], unique=False)
    op.create_table('practice_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_logs_practice_id'), 'practice_logs', ['practice_id'], unique=False)
    op.create_index(op.f('ix_practice_logs_user_id'), 'practice_logs', ['user_id'], unique=False)
    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tradition', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=False),
    sa.Column('common_mistakes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practices_name'), 'practices', ['name'], unique=True)
    op.create_index(op.f('ix_practices_tradition'), 'practices', ['tradition'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tradition', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chapters_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_sources_title'), 'sources', ['title'], unique=False)
    op.create_index(op.f('ix_sources_tradition'), 'sources', ['tradition'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_source_id'), 'chapters', ['source_id'], unique=False)
    op.create_table('content_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['content_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', name='uq_content_embedding_chunk')
    )
    op.create_index(op.f('ix_content_embeddings_chunk_id'), 'content_embeddings', ['chunk_id'], unique=False)
    op.create_table('verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('verse_number', sa.Integer(), nullable=False),
    sa.Column('canonical_reference', sa.String(length=255), nullable=False),
    sa.Column('sanskrit', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('life_application', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verses_canonical_reference'), 'verses', ['canonical_reference'], unique=True)
    op.create_index(op.f('ix_verses_chapter_id'), 'verses', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_verses_source_id'), 'verses', ['source_id'], unique=False)
    op.create_table('cross_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_verse_id', sa.Integer(), nullable=False),
    sa.Column('to_verse_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_references_from_verse_id'), 'cross_references', ['from_verse_id'], unique=False)
    op.create_index(op.f('ix_cross_references_relation_type'), 'cross_references', ['relation_type'], unique=False)
    op.create_index(op.f('ix_cross_references_to_verse_id'), 'cross_references', ['to_verse_id'], unique=False)
    op.create_table('verse_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verse_id', 'concept_id', name='uq_verse_concept')
    )
    op.create_index(op.f('ix_verse_concepts_concept_id'), 'verse_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_verse_concepts_verse_id'), 'verse_concepts', ['verse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verse_concepts_verse_id'), table_name='verse_concepts')
    op.drop_index(op.f('ix_verse_concepts_concept_id'), table_name='verse_concepts')
    op.drop_table('verse_concepts')
    op.drop_index(op.f('ix_cross_references_to_verse_id'), table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_relation_type'), table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_from_verse_id'), table_name='cross_references')
    op.drop_table('cross_references')
    op.drop_index(op.f('ix_verses_source_id'), table_name='verses')
    op.drop_index(op.f('ix_verses_chapter_id'), table_name='verses')
    op.drop_index(op.f('ix_verses_canonical_reference'), table_name='verses')
    op.drop_table('verses')
    op.drop_index(op.f('ix_content_embeddings_chunk_id'), table_name='content_embeddings')
    op.drop_table('content_embeddings')
    op.drop_index(op.f('ix_chapters_source_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_sources_tradition'), table_name='sources')
    op.drop_index(op.f('ix_sources_title'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_practices_tradition'), table_name='practices')
    op.drop_index(op.f('ix_practices_name'), table_name='practices')
    op.drop_table('practices')
    op.drop_index(op.f('ix_practice_logs_user_id'), table_name='practice_logs')
    op.drop_index(op.f('ix_practice_logs_practice_id'), table_name='practice_logs')
    op.drop_table('practice_logs')
    op.drop_index(op.f('ix_content_chunks_source_label'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_entity_type'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_entity_id'), table_name='content_chunks')
    op.drop_table('content_chunks')
    op.drop_index(op.f('ix_concepts_name'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_entity_type'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_entity_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_table('ask_logs')
    # ### end Alembic commands ###
